### ISSUE TITLE
DraggableWidget是否可以实现Aero snap效果？

### ISSUE THREAD

**Issue by Bringer-of-Light** [wangwenx190/Qt-Frameless-Draggable-Window#1]
看了DraggableWidget类的实现，可以实现拖动效果。
但是，在win7及以上，拖动窗口时，鼠标触碰到桌面顶端，可以自动最大化，鼠标触碰到桌面左端，窗口可以自动调整大小，以正好占满桌面左半边等。
双击标题栏，可以最大化窗口，看起来DraggableWidget类是不能实现的。

而且源仓库Windows版是支持拖动的，有两个方法setTitleBar() 和addIgnoreWidget()配合，可以实现完美模拟原生标题栏效果。

**Comment by wangwenx190** [comment]
@Bringer-of-Light 您好，这个仓库就是我fork自您的代码仓库，我在您原来代码的基础上做了些符合我个人需求的改动，DraggableWidget只是实现了可以拖动窗口的效果。原本这个类中有我使用Qt函数模仿DWM特性的代码，但实际效果远远比不上您所实现的效果，所以我就把那一部分代码都去掉了，只留下了拖动窗口的代码。我已经将您的代码用在我的项目中了，效果很棒，感谢您开源。我修改过的文件头部我都有声明原作者和源代码仓库的网址，开源许可协议也一直留着，请您放心。

**Comment by Bringer-of-Light** [comment]
@wangwenx190 
是这样的，我看到您的readme里面说，“虽然源仓库是不支持无边框窗口拖动的”，但实际上源仓库是支持的。所以希望这一句您能改一下，免得读者误会。

**Comment by Bringer-of-Light** [comment]
@wangwenx190 
很高兴能对您有所帮助。这些代码我没有充分测试，所以您用在项目中的话，不同的windows系统还是多测一测好。

**Comment by wangwenx190** [comment]
@Bringer-of-Light 确实是我表达有问题，现在的写法确实容易产生歧义，不好意思了，我马上改。测试的话我会进行的，有问题的话我会在您的代码仓库下开issue的。

**Comment by wangwenx190** [comment]
@Bringer-of-Light 已经更改自述文件，感谢您的提醒和配合。
